export default {
  titlesList: [
    "Easy Sugar Cookies",
    "Chocolate Chip Cookies",
    "Baked Feta Pasta",
    "Honey Glazed Salmon",
    "Shrimp Fried Rice",
    "Cauliflower Pasta",
    "Chicken Fajitas",
    "Penne Vodka",
    "Cilantro Lime Chicken",
    "Pumpkin Curry",
    "Shrimp Scampi",
    "Mushroom Pasta",
    "Butter Chicken",
    "Chicken Quesadillas",
    "Tomato Soup",
    "Fettuccine Alfredo",
    "Pork Dumplings",
    "Beef Stroganoff",
    "Caprese Chicken",
    "Chicken Meatballs",
    "Beef Tenderloin",
    "Cajun Butter Steak",
    "Chicken Chow Mein",
  ],
  tagsList: [
    { tag: "Vegetarian", selected: false, id: "1" },
    { tag: "Vegan", selected: false, id: "2" },
    { tag: "Kosher", selected: false, id: "3" },
    { tag: "Halal", selected: false, id: "4" },
    { tag: "Italian", selected: false, id: "5" },
    { tag: "Korean", selected: false, id: "6" },
    { tag: "Chinese", selected: false, id: "7" },
    { tag: "Greek", selected: false, id: "8" },
    { tag: "French", selected: false, id: "9" },
    { tag: "Chinese", selected: false, id: "10" },
    { tag: "Japanese", selected: false, id: "11" },
    { tag: "Mexican", selected: false, id: "12" },
    { tag: "Breakfast", selected: false, id: "13" },
    { tag: "Lunch", selected: false, id: "14" },
    { tag: "Dinner", selected: false, id: "15" },
    { tag: "Dessert", selected: false, id: "16" },
  ],
};
