export default {
  titlesList: [
    "Easy Sugar Cookies",
    "Chocolate Chip Cookies",
    "Baked Feta Pasta",
    "Honey Glazed Salmon",
    "Shrimp Fried Rice",
    "Cauliflower Pasta",
    "Chicken Fajitas",
    "Penne Vodka",
    "Cilantro Lime Chicken",
    "Pumpkin Curry",
    "Shrimp Scampi",
    "Mushroom Pasta",
    "Butter Chicken",
    "Chicken Quesadillas",
    "Tomato Soup",
    "Fettuccine Alfredo",
    "Pork Dumplings",
    "Beef Stroganoff",
    "Caprese Chicken",
    "Chicken Meatballs",
    "Beef Tenderloin",
    "Cajun Butter Steak",
    "Chicken Chow Mein",
  ],
  ingredientsList: [
    "1 tbsp. coconut oil",
    "1 yellow onion, chopped",
    "2 cloves garlic, minced",
    "1 tbsp. curry powder",
    "1/2 tsp. cayenne pepper",
    "1 tsp. cumin seeds",
    "1 green chili, diced",
    "2 tsp. grated ginger",
    "1 tsp. turmeric",
    "1/4 c. chopped cilantro",
    "2 c. all-purpose flour",
    "1/2 tsp. salt",
    "2 tablespoons olive oil",
    "4 slices bacon",
    "1/2 cup basil leaves",
    "1/4 cup parsley leaves",
    "1/4 cup dill",
    "3 tbsp. plain yogurt",
    "1 cup cherry tomatoes",
    "2 1/2 sticks butter",
    "1 c. brown sugar",
    "2 tsp. vanilla extract",
    "2 eggs",
    "2 3/4 c. flour",
    "2 lb. chicken wings",
    "4 tbsp. melted butter",
    "1/2 tsp. garlic powder",
    "1 c. heavy cream",
    "1 c. powdered sugar",
    "1 tsp. cinnamon",
    "1/2 tsp. ground nutmeg",
    "3 tsp. lemon zest",
    "1/2 onion, chopped",
    "2 cloves garlic, minced",
    "1 tsp. dried oregano",
    "1 tsp. smoked paprika",
    "1 c. white rice",
    "1/2 tsp. chili powder",
    "1/2 tsp. ground cumin",
    "1/2 tsp. dried oregano",
    "1 avocado, sliced",
    "2 green onions, sliced",
  ],
  tagsList: [
    { tag: "Breakfast", selected: false, id: "1" },
    { tag: "Lunch", selected: false, id: "2" },
    { tag: "Dinner", selected: false, id: "3" },
    { tag: "Dessert", selected: false, id: "4" },
    { tag: "Vegetarian", selected: false, id: "5" },
    { tag: "Vegan", selected: false, id: "6" },
    { tag: "Kosher", selected: false, id: "7" },
    { tag: "Halal", selected: false, id: "8" },
    { tag: "Italian", selected: false, id: "9" },
    { tag: "Korean", selected: false, id: "10" },
    { tag: "Chinese", selected: false, id: "11" },
    { tag: "Greek", selected: false, id: "12" },
    { tag: "French", selected: false, id: "13" },
    { tag: "Chinese", selected: false, id: "14" },
    { tag: "Japanese", selected: false, id: "15" },
    { tag: "Mexican", selected: false, id: "16" },
    { tag: "Indian", selected: false, id: "17" },
  ],
}
